title: 'paul le'
tagline: ''

author:
  name: 'Paul Le'

google-ID: 'UA-111549056-1'

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: '/blog/'}
- {name: 'Contact', url: 'contact.html'}

main-projects:
- {name: 'Physics in Motion', image: 'physics-in-motion.png', file: 'projects/physics-in-motion.html', blurb: 'How physics was meant to be taught.'}
- {name: 'applepy', image: 'gun.jpg', file: 'projects/applepy.html', blurb: 'The intersection between physics and computer science.'}
- {name: 'Jekyll Themes', image: 'box.jpg', file: 'projects/jekyll-themes.html', blurb: 'Static website projects.'}

side-projects:
- {name: 'FogBugz + Trello Integration ', image: '', file: 'projects/fogbugz-trello-integration.html', blurb: 'Improving workflow at work.'}

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://www.instagram.com/paululele/'}
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/lenpaul/'}
