title: 'paul le'
tagline: ''

author:
  name: 'Paul Le'

google-ID: 'UA-111549056-1'

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog'}
- {name: 'Contact', url: 'contact.html'}

main-projects:
- {name: 'Physics in Motion', image: 'physics-in-motion.png', file: 'projects/physics-in-motion.html', blurb: 'How physics was meant to be taught.'}
#- {name: 'applepy', image: 'gun.jpg', file: 'projects/applepy.html', blurb: 'The intersection between physics and computer science.'}
- {name: 'Jekyll Themes', image: 'box.jpg', file: 'projects/jekyll-themes.html', blurb: 'Static website templates for GitHub pages.'}
- {name: 'Improving Support Workflow', image: '', file: 'projects/improving-support-workflow.html', blurb: 'Improving support workflow through human-centered design.'}
- {name: 'Human-centred design in hospital technology', image: '', file: 'projects/human-centred-design-in-hospital-technology.html', blurb: 'Using human-centred design to solve a problem using technology in the hospital.'}

#side-projects:
#- {name: '', image: '', file: '', blurb: ''}

social:
- {icon: 'github', link: 'https://github.com/lenpaul'}
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}
