title: pl
tagline: Paul Le

author:
  name: Paul Le

menu:
- {name: 'About', url: ''}
- {name: 'Projects', url: 'projects.html'}
- {name: 'Blog', url: 'blog.html'}
- {name: 'Contact', url: 'contact.html'}

projects:
- {name: 'Physics in Motion', image: 'physics-in-motion.png', file: 'projects/physics-in-motion.html', blurb: 'How physics was meant to be taught.'}
- {name: 'applepy', image: 'gun.jpg', file: 'projects/applepy.html', blurb: 'The intersection between physics and computer science.'}
- {name: 'Jekyll Themes', image: 'box.jpg', file: 'projects/jekyll-themes.html', blurb: 'Static website projects.'}

social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'instagram', link: 'https://www.instagram.com/paululele/'}
- {icon: 'github', link: 'https://github.com/LeNPaul'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/lenpaul/'}
